repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--line-length=100]
      language_version: python3.9
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      additional_dependencies: [types-redis==4.6.0.2]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
