[tool.poetry]
name = "deltalake-redis-lock"
version = "0.0.1"
description = "deltalake-redis-lock"
authors = ["Simon Thelin"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
deltalake = "^0.10.0"
redis = "^4.6.0"
pandas = "^2.0.3"
pyarrow = "^12.0.1"

[tool.poetry.dev-dependencies]
pre-commit = "^3.3.3"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
joblib = "1.3.1"

